[package]
name = "rustypwn_derive"
version = "0.1.0"
authors = ["Anciety <anciety512@gmail.com>"]
edition = "2018"

[dependencies]
proc-macro2 = "0.4"
quote = "0.6"

[lib]
proc-macro = true

[dependencies.syn]
version = "0.15"
features = ["full"]
