[package]
name = "rustypwn_derive"
version = "0.1.0"
authors = ["Anciety <anciety512@gmail.com>"]
edition = "2018"

[dependencies]
proc-macro2 = "0.4"
syn = "0.15"
quote = "0.6"

[lib]
proc-macro = true
